import { 
    PUBLIC_APPWRITE_DATABASE_ID,
    PUBLIC_APPWRITE_COLLECTION_SERVICES,
    PUBLIC_APPWRITE_COLLECTION_GALLERY,
    PUBLIC_APPWRITE_COLLECTION_APPOINTMENTS
} from '$env/static/public';

export const config = {
    databaseId: PUBLIC_APPWRITE_DATABASE_ID,
    collections: {
        services: PUBLIC_APPWRITE_COLLECTION_SERVICES,
        gallery: PUBLIC_APPWRITE_COLLECTION_GALLERY,
        appointments: PUBLIC_APPWRITE_COLLECTION_APPOINTMENTS
    }
};
