import { 
    PUBLIC_APPWRITE_DATABASE_ID,
    PUBLIC_APPWRITE_COLLECTION_SERVICES,
    PUBLIC_APPWRITE_COLLECTION_GALLERY,
    PUBLIC_APPWRITE_COLLECTION_APPOINTMENTS,
    PUBLIC_APPWRITE_ENDPOINT,
    PUBLIC_APPWRITE_PROJECT_ID
} from '$lib/env.js';

export const config = {
    databaseId: PUBLIC_APPWRITE_DATABASE_ID,
    collections: {
        services: PUBLIC_APPWRITE_COLLECTION_SERVICES,
        gallery: PUBLIC_APPWRITE_COLLECTION_GALLERY,
        appointments: PUBLIC_APPWRITE_COLLECTION_APPOINTMENTS
    }
};
